### PR TITLE
feat: add maven support

### LINKED ISSUE #7: add support for Maven dependencies

### PR DESCRIPTION
**Pull request by randomicecube**
Closed the previous PR because it was too cluttered, should be way easier to follow this one
Provenance and deprecation checks not currently supported
@Stamp9 I noticed that forks are only checked if no provenance was found, should this still be the case?

Closes #7

### CODE REVIEW

**Comment by randomicecube** [comment]
Btw, the package I've been using to test this:

`python main.py -p netty/netty -v netty-4.2.0.Alpha5 -s -pm maven`

**Comment by monperrus** [comment]
nice!
could you do it for Spoon?

**Comment by randomicecube** [comment]
Ran it for Spoon. FYI, changed the check for inaccessible tags -- now we only count the amount of them which we can't find in accessible GitHub repos, the previous reports included this + inaccessible repos as well; IMO it didn't really make sense to include both in the count since the table itself only shows the ones from accessible repos. I can roll it back if you prefer it to be how it was before, though.

`python main.py -p INRIA/spoon -v v11.1.1-beta-9 -s -pm maven`


# Software Supply Chain Report of INRIA/spoon - v11.1.1-beta-9


<details>
    <summary>How to read the results :book: </summary>
    
 Dirty-waters has analyzed your project dependencies and found different categories for each of them:

    
 - ⚠️⚠️⚠️ : high severity 

    
 - ⚠️⚠️: medium severity 

    
 - ⚠️: low severity 

</details>
        

 ### Total packages in the supply chain: 17


:heavy_exclamation_mark: Packages with no Source Code URL(⚠️⚠️⚠️): 0

:no_entry: Packages with Github URLs that are 404(⚠️⚠️⚠️): 4

:wrench: Packages with accessible source code repos but inaccessible GitHub tags(⚠️⚠️⚠️): 5

:x: Packages that are deprecated(⚠️⚠️): 0

:cactus: Packages that are forks(⚠️⚠️): 0

:black_square_button: Packages without provenance(⚠️): 0


### Fine grained information

:dolphin: For further information about software supply chain smells in your project, take a look at the following tables.

<details>
    <summary>Source code links that could not be found(4)</summary>
        


|   index | package_name                          | github_url                                                     | github_exists   |
|--------:|:--------------------------------------|:---------------------------------------------------------------|:----------------|
|       1 | org.slf4j:slf4j-api@2.0.16            | https://github.com/qos-ch/slf4j/slf4j-parent/slf4j-api         | False           |
|       2 | org.assertj:assertj-core@3.26.3       | https://github.com/assertj/assertj/assertj-parent/assertj-core | False           |
|       3 | com.google.guava:guava@33.3.1-jre     | https://github.com/google/guava/guava                          | False           |
|       4 | ch.qos.logback:logback-classic@1.5.10 | https://github.com/qos-ch/logback/logback-classic              | False           |
</details>

<details>
    <summary>List of packages with available source code repos but with inaccessible tags(5)</summary>
        


| package_name                                       | release_tag_exists   | tag_version   | github_url                                      | tag_related_info               |   status_code_for_release_tag |
|:---------------------------------------------------|:---------------------|:--------------|:------------------------------------------------|:-------------------------------|------------------------------:|
| org.eclipse.jdt:org.eclipse.jdt.core@3.38.0        | False                | 3.38.0        | https://github.com/eclipse-jdt/eclipse.jdt.core | Tags are not found in the repo |                           404 |
| org.apache.maven:maven-model@3.6.0                 | False                | 3.6.0         | https://github.com/apache/maven                 | Tags are not found in the repo |                           404 |
| com.fasterxml.jackson.core:jackson-databind@2.18.0 | False                | 2.18.0        | https://github.com/fasterxml/jackson-databind   | Tags are not found in the repo |                           404 |
| com.mysema.querydsl:querydsl-core@3.7.4            | False                | 3.7.4         | https://github.com/querydsl/querydsl            | Tags are not found in the repo |                           404 |
| org.apache.maven.shared:maven-invoker@3.3.0        | False                | 3.3.0         | https://github.com/apache/maven-invoker         | Tags are not found in the repo |                           404 |
</details>
The package manager (maven) does not support checking for deprecated packages.

No package is from fork.

### Call to Action:

                      
<details>
    <summary>👻What do I do now? </summary>
        For packages without source code & accessible release tags:  

        Pull Request to the maintainer of dependency, requesting correct repository metadata and proper tagging. 

        
For deprecated packages:

        1. Confirm the maintainer’s deprecation intention 
        2. Check for not deprecated versions
        
For packages without provenance:

        Open an issue in the dependency’s repository to request the inclusion of provenance and build attestation in the CI/CD pipeline. 
        
For packages that are forks

        Inspect the package and its GitHub repository to verify the fork is not malicious.
</details>



---

Report created by [dirty-waters](https://github.com/chains-project/dirty-waters/).

Report created on 2024-11-07 11:38:25
- Tool version: c454c524
- Project Name: INRIA/spoon
- Project Version: v11.1.1-beta-9

**Comment by Stamp9** [comment]
> IMO it didn't really make sense to include both in the count since the table itself only shows the ones from accessible repos.

Hi, @randomicecube , yea I think the newer one makes more sense! Great work!

**Comment by Stamp9** [comment]
> I noticed that forks are only checked if no provenance was found, should this still be the case?

Hi, @randomicecube, fork is the information we got from GitHub, it didn't do check.
The code you mentioned [here](https://github.com/chains-project/dirty-waters/blob/a02707b01ddb4f9462ccfc024a1299de6561f2a2/tool/static_analysis.py#L428C1-L432C100) is trying to do `check_name_match` where I wanted to check if the `package_name` in `package.json` file match the package name in npm registry. But turns out it is not very efficient, so we didn't consider it in the end. Feel free to refactor the code as well as remove the argument. Thanks!

**Review by Stamp9 — APPROVED** [review]

**Comment by Stamp9** [comment]
One potential improvement might be to remove the initial points(rather than show 0) if they are not supported(such as deprecation for maven).

**Comment by randomicecube** [comment]
> One potential improvement might be to remove the initial points(rather than show 0) if they are not supported(such as deprecation for maven).

I think it would be nice to still show them, but with a green tick emoji, to point out that everything's nice now, but while also emphasizing that the check still happened.

@monperrus @Stamp9 what do you think?

**Comment by monperrus** [comment]
I agree to remove the unsupported features from the report.

**Pull request merged**
