### PR TITLE
feat: add nix flake

### PR DESCRIPTION
**Pull request by randomicecube**
Adding a Nix flake to the repo -- for now, it'll read the `requirements.txt` file and create an environment accordingly. Future versions could, for example, include openJDK, for when Java support is developed, and so on.

### CODE REVIEW

**Comment by randomicecube** [comment]
@Stamp9 Could you confirm whether every single dependency mentioned in `requirements.txt` is used? I'm asking because, for the flake to (currently) work, I commented out 4 packages which aren't in nixPkgs, ran the example script in the README (for MetaMask) and it worked. As such, I think we should investigate whether every single dependency here is needed, and remove the ones which aren't

BTW, I'll add back soon the assertion of python package versions in the flake, after we know every python dependency which is effectively needed (and their versions)

**Comment by Stamp9** [comment]
> @Stamp9 Could you confirm whether every single dependency mentioned in `requirements.txt` is used? I'm asking because, for the flake to (currently) work, I commented out 4 packages which aren't in nixPkgs, ran the example script in the README (for MetaMask) and it worked. As such, I think we should investigate whether every single dependency here is needed, and remove the ones which aren't
> 
> BTW, I'll add back soon the assertion of python package versions in the flake, after we know every python dependency which is effectively needed (and their versions)

Hi, @randomicecube, thanks for checking! I re-generate the `requirements.txt` by using `pipreqs`, feel free to check.

**Comment by randomicecube** [comment]
@Stamp9 should be fine now, thanks!

**Comment by monperrus** [comment]
👍

**Comment by Stamp9** [comment]
Hi, @randomicecube, I re-generate the requirements file in virtual environment by using `pip freeze` to fix issue https://github.com/chains-project/dirty-waters/issues/23#issuecomment-2433220443, please let me know if there's any issues, thanks!

**Pull request merged**
